Repository TitovCompany/Visionlife_FE, pull requests merged in 2025-02, with the labels that each got.

#29 🐛 Fix : 부모 경로가 자식 경로에서 활성화되는 문제 해결
  src/components/Tab/TabNavLinkItem.tsx
Labels: bug, UI / UX

#33 refactor: HISTORY에있는 중앙의 제목텍스트 왼쪽 정렬되게 수정
  src/features/profile/pages/History.tsx
Labels: bug, UI / UX

#37 Feat : 리포트 양식 추가
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/ui_ux_request.md
Labels: documentation

#35 refactor: 뉴스 컴포넌트 변경
  src/features/news/index.tsx
  src/features/news/pages/NewsDetail.tsx
Labels: UI / UX, News

#57 :recycle: refactor - Footer 컴포넌트 리팩토링 및 캐싱
  src/layout/Footer.tsx
  src/layout/Footer/FooterColumn.tsx
  src/layout/Footer/index.tsx
  src/layout/RootLayout.tsx
Labels: bug, UI / UX, Component

#60 ♻️ Refactor : Utex 내 컴포넌트 추가(수정) 및 디자인 수정
  src/components/ImageCard.tsx
  src/data/business/utex_features.json
  src/features/business-overview/pages/Utex.tsx
  src/layout/Footer/index.tsx
  src/routes.ts
Labels: bug, UI / UX, BusinessOverview

#65 refactor: 제품 개요 섹션 리스트 정렬 방식 변경
  src/features/business-overview/pages/Utex.tsx
Labels: UI / UX, BusinessOverview

#69 ♻️ Refactor : NavMenu.tsx 컴포넌트 생성 및 네비게이션 구조 개선
  src/components/Logo.tsx
  src/layout/Footer/FooterColumn.tsx
  src/layout/Footer/index.tsx
  src/layout/Navbar/NavbarDesktop.tsx
  src/layout/Navbar/NavbarMenu.tsx
  src/layout/Navbar/NavbarMobile.tsx
  src/layout/Navbar/index.tsx
  src/layout/Navigation.tsx
  src/layout/RootLayout.tsx
Labels: UI / UX, Component

#66 :recycle: Refactor - Footer 반응형 디자인 수정
  src/layout/Footer/FooterColumn.tsx
  src/layout/Footer/index.tsx
Labels: UI / UX, Component

#72 ♻️ refactor: NavbarMobileMenu.tsx 컴포넌트 생성 및 모바일 네비게이션 구조 개선
  src/layout/Navbar/NavbarMenu.tsx
  src/layout/Navbar/NavbarMobile.tsx
  src/layout/Navbar/NavbarMobileMenu.tsx
Labels: UI / UX, Component

#71 feat : 외부 클릭 시 모바일 메뉴 닫히는 훅 생성
  src/hooks/useOnClickOutside.ts
Labels: Component, Type

#76 ♻️ refactor: 레이아웃 개선 및 CurrentInfoPath 컴포넌트 추가
  index.html
  src/data/businessOverview.json
  src/features/business-overview/components/BenefitList.tsx
  src/features/business-overview/components/CurrentInfoPath.tsx
  src/features/business-overview/components/OverviewList.tsx
  src/features/business-overview/index.tsx
  src/features/business-overview/pages/Overview.tsx
  src/features/business-overview/pages/SelectBusiness.tsx
  src/features/business-overview/pages/Utex.tsx
  src/features/catalog/index.tsx
  src/features/home/index.tsx
  src/features/news/index.tsx
  src/features/profile/index.tsx
  src/index.css
  src/layout/PageLayout.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
Labels: UI / UX, Component

#80 ♻️ refactor: News 컴포넌트 리팩토링
  src/components/Pagination.tsx
  src/data/news.json
  src/features/home/index.tsx
  src/features/news/components/FeaturedNews.tsx
  src/features/news/components/NewsCardList.tsx
  src/features/news/components/NewsList.tsx
  src/features/news/index.tsx
  src/features/news/pages/News.tsx
  src/features/news/pages/NewsDetail.tsx
  src/hooks/usePagenation.ts
  src/routes.ts
Labels: Component, News, Hook

#81 refactor: 메인페이지 서비스 SectionAbout_Design2 애니메이션 개선
  src/features/home/components/SectionAbout_Design2.tsx
Labels: UI / UX, Component, Home

#89 :sparkle: feat: 코드 난독화 및 보안 강화
  dist/assets/index-BBHWtrQv.css
  dist/assets/index-D2vj2Val.js
  dist/index.html
  index.html
  package-lock.json
  public/robots.txt
  vite.config.ts
Labels: SEO

#90 refactor: 4색잉크 아이콘 삽입
  public/img/product/ink/p3.png
Labels: UI / UX, BusinessOverview

#88 refactor: 기업 연혁 반응형 페이지 제목,텍스트 왼쪽부터 출력되게 변경
  src/features/profile/pages/History.tsx
Labels: UI / UX, Component, BusinessOverview

#91 :bug: fix: 내비게이션 버그 픽스
  src/layout/Navbar/NavbarDesktop.tsx
  src/layout/Navbar/NavbarMenu.tsx
Labels: UI / UX, Component

#96 refactor: contactus 지도 사진 삽입
  public/img/contactus/map.png
  src/features/profile/pages/ContactUs.tsx
Labels: UI / UX, Component, BusinessOverview

#93 refactor:Coltex.mp4데이터 추가 및 영상 데이터 삽입
  src/data/catalogData.json
  src/data/catalogdata/utex 사업계획서(영문)-1.pdf
  src/data/catalogdata/utex 사업계획서(중문).pdf
  src/data/catalogpdf/utex 사업계획서(영문)-1.pdf
  src/data/catalogpdf/utex 사업계획서(중문).pdf
Labels: Catalog

#87 refactor: utex_features.json줄바꿈 수정
  src/data/business/utex_features.json
Labels: UI / UX, BusinessOverview

#92 refactor:메인페이지 및 기업소개 히어로섹션 이미지 변경
  public/img/banner/p1.jpg
  public/img/home/p2.jpg
Labels: UI / UX

#95 refactor: 모든 소식 보기 클릭시 언론 보도 페이지로 이동하도록 변경
  src/features/home/components/MoreNewsSection.tsx
Labels: Component, Home

#103 refactor: 주소 아이콘 백그라운드 크기 다른 아이콘들과 동일하게 변경
  src/features/profile/pages/ContactUs.tsx
Labels: UI / UX, Component, BusinessOverview

#105 ♻️ refactor: Profile.tsx 내 반복 요소 JSON 분리 및 스크롤 애니메이션 적용
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/components/Map/NaverMap.tsx
  src/data/profile/overview.json
  src/features/catalog/components/.gitkeep
  src/features/catalog/components/DownloadItem.tsx
  src/features/catalog/index.tsx
  src/features/catalog/types/.gitkeep
  src/features/catalog/types/catalog.d.ts
  src/features/profile/pages/ContactUs.tsx
  src/features/profile/pages/History.keeps.tsx
  src/features/profile/pages/History.tsx
  src/features/profile/pages/Profile.tsx
  src/features/test/pages/ScrollSnap.tsx
  src/hooks/useScrollAnimation.ts
  src/layout/Navbar/index.tsx
  src/routes.ts
Labels: UI / UX, Component, Service

#108 refactor: 사업 소개 페이지 모바일 좌우 여백 추가 및 레이아웃 정리
  src/features/business-overview/pages/Overview.tsx
Labels: UI / UX, Component, BusinessOverview

#111 ♻️ Refactor - 메인페이지 레이아웃 리뉴얼
  public/img/home/p4.jpg
  public/img/home/p5.jpg
  public/img/home/p6.jpg
  public/img/home/p7.jpg
  public/img/home/p8.jpg
  src/data/home/intro.json
  src/features/home/components/MoreNewsSection.tsx
  src/features/home/index.tsx
  src/layout/BusinessSectionLayout.tsx
Labels: UI / UX, Component, Home

#112 refactor 회사소개 모바일 화면 가로 스크롤 이슈 수정
  src/features/profile/pages/Profile.tsx
Labels: UI / UX, Component, BusinessOverview

#115 refactor: footer 레이아웃 수정 및 페이지네이션 cursor-pointer 추가
  src/components/Pagination.tsx
  src/layout/Footer/index.tsx
Labels: UI / UX, Component

#127 Vision Section 스크롤 애니메이션 적용 및 비즈니스 파트너 섹션 레이아웃 개선
  public/img/profile/p1.jpg
  public/img/profile/p3.jpg
  public/img/profile/p4.jpg
  src/data/profile/comment.json
  src/data/profile/vision.json
  src/features/profile/components/VisionCarousel.tsx
  src/features/profile/components/VisionDesign_1.tsx
  src/features/profile/components/VisionScroll.tsx
  src/features/profile/components/keep.tsx
  src/features/profile/pages/Profile.tsx
  src/hooks/useScrollSlide.ts
Labels: Component, Profile

#126 refactor: 뉴스페이지 모바일 화면의 좌우 여백 수정
  src/features/news/components/NewsCardList.tsx
Labels: UI / UX, Component, News

#124 refactor 메인페이지 반응형웹 테블릿 크기일시 모바일처럼 햄버거 메뉴 나오게 수정 및 로고 위치 조정
  src/layout/Navbar/NavbarDesktop.tsx
  src/layout/Navbar/NavbarMobile.tsx
Labels: bug, UI / UX, Component

#123 -refactor 메인페이지 모바일 화면 가로 스크롤 숨김 적용
  src/features/home/index.tsx
Labels: bug, UI / UX, Component, Home

#130 :art: Design : 사업 소개 및 개요 페이지 디자인 개선 및 반응형 작업
  public/img/business/p1.jpg
  public/img/business/p2.jpg
  public/img/business/p3.jpg
  src/data/business/biz_info.json
  src/data/business/biz_point.json
  src/features/business-overview/components/BusinessPoint.tsx
  src/features/business-overview/components/LegacyDesign.tsx
  src/features/business-overview/pages/Overview.tsx
Labels: Component, BusinessOverview

#131 :bug: fix - 네이버 맵이 정상적으로 렌더링되지 않는 문제 해결
  public/img/contactus/map.png
  src/components/Map/NaverMap.tsx
  src/features/profile/pages/ContactUs.tsx
Labels: bug, Component

#133 ♻️ refactor - UTEX 소개 페이지 디자인 수정 및 Business Overview 키 변경
  src/components/ImageCard.tsx
  src/data/business/utex_comparison.json
  src/features/business-overview/components/ComparisonArticle.tsx
  src/features/business-overview/pages/Overview.tsx
  src/features/business-overview/pages/Utex.tsx
  src/features/business-overview/types/.gitkeep
  src/features/business-overview/types/business.d.ts
  src/features/test/pages/TestPage.tsx
  src/routes.ts
Labels: Component, BusinessOverview

#134 :recycle: refactor - Utex 섬유 염색 공정 비교 섹션 디자인 수정
  src/features/business-overview/components/BenefitList.tsx
  src/features/business-overview/components/CurrentInfoPath.tsx
  src/features/business-overview/components/LegacyDesign.tsx
  src/features/business-overview/components/OverviewList.tsx
  src/features/business-overview/pages/Utex.tsx
  src/hooks/useInfiniteCarousel.ts
  src/routes.ts
Labels: Component, BusinessOverview

#136 ♻️ refactor - 폴더 구조 및 임시 애니메이션 적용
  src/components/animation/.gitkeep
  src/features/business-overview/components/BusinessCard.tsx
  src/features/business-overview/components/BusinessPoint.tsx
  src/features/business-overview/components/ComparisonArticle.tsx
  src/features/business-overview/components/UtexComparison.tsx
  src/features/business-overview/components/UtexFeatures.tsx
  src/features/business-overview/components/UtexInkSystem.tsx
  src/features/business-overview/components/UtexOverview.tsx
  src/features/business-overview/index.tsx
  src/features/business-overview/pages/Overview.tsx
  src/features/business-overview/pages/SelectBusiness.tsx
  src/features/business-overview/pages/Utex.tsx
  src/features/business/components/BusinessCard.tsx
  src/features/business/components/UtexComparison.tsx
  src/features/business/components/UtexFeatures.tsx
  src/features/business/components/UtexInkSystem.tsx
  src/features/business/components/UtexOverview.tsx
  src/features/business/pages/Overview.tsx
  src/features/business/pages/SelectBusiness.tsx
  src/features/business/pages/Utex.tsx
  src/features/news/pages/News.tsx
  src/features/news/pages/NewsDetail.tsx
  src/features/profile/pages/Profile.tsx
  src/routes.ts
Labels: UI / UX, Component, Profile, Home, BusinessOverview, Refactor

#142 :sparkle: feat - 캐러셀 슬라이드 생성 및 적용
  package-lock.json
  package.json
  src/components/Carousel.tsx
  src/components/SectionTitle.tsx
  src/features/news/components/NewsCardList.tsx
  src/features/news/pages/News.tsx
Labels: UI / UX, Component, News

#151 :recycle: refactor - tailwind css 커스텀 반응형 추가 (CL: 454)
  src/index.css
Labels: Chore

#152 refactor: ContactUs 컴포넌트 레이아웃 및 반응형 스타일링 개선
  src/features/profile/pages/ContactUs.tsx
Labels: UI / UX, Component, BusinessOverview

#154 ♻️ refactor - Home & Footer 컴포넌트 반응형 디자인 개선 (PC 대응)
  .github/PULL_REQUEST_TEMPLATE.md
  src/features/home/index.tsx
  src/features/news/components/NewsCard.tsx
  src/features/profile/index.tsx
  src/features/profile/pages/ContactUs.tsx
  src/features/profile/pages/Profile.tsx
  src/layout/BusinessSectionLayout.tsx
  src/layout/Footer/FooterColumn.tsx
  src/layout/HeroSection.tsx
Labels: UI / UX, Component, Home, News

#157 ♻️ refactor: 모바일 환경에서 TabNavbar 대신 드롭다운 메뉴 적용
  src/components/Dropdown.tsx
  src/features/profile/index.tsx
  src/features/profile/pages/ContactUs.tsx
  src/hooks/useToggle.ts
  src/layout/Footer/FooterColumn.tsx
Labels: UI / UX, Component, Profile, Hook

#156 refactor: catalog 페이지 레이아웃 및 반응형 개선
  src/features/catalog/components/DownloadItem.tsx
  src/features/catalog/index.tsx
Labels: UI / UX, Component, Catalog

#158 ♻️ refactor: Business Overview 반응형 작업
  src/features/business/components/BusinessPoint.tsx
  src/features/business/pages/Overview.tsx
Labels: UI / UX, Component, BusinessOverview

#159 ♻️ refactor: Business Utex 반응형 작업
  src/features/business/components/UtexComparison.tsx
  src/features/business/components/UtexFeatures.tsx
  src/features/business/components/UtexInkSystem.tsx
  src/features/business/components/UtexOverview.tsx
  src/features/business/pages/Utex.tsx
Labels: UI / UX, Component, BusinessOverview

#163 워크플로우 수정
  .github/workflows/main.yml
Labels: Chore

#160 refactor: 뉴스 데이터 추가
  src/data/news.json
Labels: News
